name: borodenkov public blog
description:
avatar:
footer-links:
  email: borodenkov.e.a@gmail.com
  github: borodenkov
  instagram: https://www.instagram.com/borodenkov/
  linkedin: https://ru.linkedin.com/in/borodenkov
  twitter: e_borodenkov

disqus:
google_analytics: UA-73369592-1
url:
baseurl: ""
permalink: /:title/
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
sass:
  style: :expanded # You might prefer to minify using :compressed
theme: minima
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
